[package]
name = "rankforum"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.1", features = ["v4"] }
chrono = "0.4"
log = "0.4"
env_logger = "0.11.6"
hyper = "1.5.2"
tokio = { version = "1", features = ["full"] }