[package]
name = "rankforum"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.1", features = ["v4"] }
chrono = "0.4"
log = "0.4"
env_logger = "0.11.6"
rouille = "3.6.2"
rusqlite = "0.32.1"
lazy_static = "1.4.0"
